# Generated by Django 5.0.6 on 2024-07-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
