# Generated by Django 5.0 on 2024-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='dni',
            field=models.CharField(db_index=True, default='DEFAULT_DNI', max_length=255, verbose_name='Dni'),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(default='DEFAULT_DNI', max_length=255, unique=True, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='name',
            field=models.CharField(default='DEFAULT_NAME', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='DEFAULT_NAME', max_length=255, verbose_name='Name'),
        ),
    ]
